version: '3.8'

services:
  db:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: app-user
      POSTGRES_PASSWORD: app-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: docker/dev/Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PROJECT_ROOT}:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
