version: '3.8'

services:
  db:
    image: postgres:16.2-bookworm
    # Production environment variables

  web:
    environment:
      - PROJECT_NAME=my_new_project_name
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn {PROJECT_NAME}.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/path/to/static
      - media_volume:/path/to/media

  nginx:
    image: nginx:1.25-bookworm
    ports:
      - "80:80"
    volumes:
      - static_volume:/path/to/staticfiles:ro
      - media_volume:/path/to/mediafiles:ro
      - ./docker/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
