# Generated by Django 5.0.3 on 2024-03-13 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('content', models.CharField(max_length=255)),
                ('output_type', models.CharField(choices=[('animation', 'Animation'), ('audio', 'Audio'), ('boolean', 'Boolean'), ('code', 'Code'), ('document', 'Document'), ('free_text', 'Free Text'), ('graph', 'Graph'), ('html', 'HTML'), ('image', 'Image'), ('image_sequence', 'Image Sequence'), ('interactive', 'Interactive'), ('json', 'JSON'), ('link', 'Link'), ('list', 'List'), ('map', 'Map'), ('markdown', 'Markdown'), ('mermaid', 'Mermeid'), ('qr_code', 'QR Code'), ('score', 'Score'), ('table', 'Table'), ('video', 'Video'), ('xml', 'XML'), ('yaml', 'YAML')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_log', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('instructions', models.ManyToManyField(related_name='prompts', to='prompt.instruction')),
                ('rules', models.ManyToManyField(related_name='prompts', to='prompt.rule')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompt.template')),
            ],
        ),
    ]
