# Generated by Django 5.0.3 on 2024-03-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='output_type',
        ),
        migrations.AddField(
            model_name='prompt',
            name='output_format',
            field=models.CharField(choices=[('animation', 'Animation'), ('audio', 'Audio'), ('boolean', 'Boolean'), ('code', 'Code'), ('document', 'Document'), ('free_text', 'Free Text'), ('graph', 'Graph'), ('html', 'HTML'), ('image', 'Image'), ('image_sequence', 'Image Sequence'), ('interactive', 'Interactive'), ('JSON', 'JSON'), ('link', 'Link'), ('list', 'List'), ('map', 'Map'), ('markdown', 'Markdown'), ('mermaid', 'Mermeid'), ('qr_code', 'QR Code'), ('score', 'Score'), ('table', 'Table'), ('video', 'Video'), ('XML', 'XML'), ('YAML', 'YAML')], default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='template',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prompt.template'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='instructions', to='prompt.tag'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='prompt.tag'),
        ),
        migrations.AddField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rules', to='prompt.tag'),
        ),
    ]
