# Generated by Django 5.0.3 on 2024-03-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0002_tag_remove_prompt_output_type_prompt_output_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prompt.template'),
        ),
    ]
